# Generated by Django 4.2.7 on 2023-11-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=25)),
                ('year', models.IntegerField(max_length=4)),
                ('create_time', models.DateTimeField(verbose_name='create time')),
                ('last_edit_time', models.DateTimeField(verbose_name='last edit time')),
            ],
        ),
    ]
